services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - supportflow

  config-server:
    image: ace0777/supportflow-config-server
    container_name: 'config-server'
    environment:
      - CONFIG_SERVER_URI=https://github.com/Ace0777/support-flow-config
      - CONFIG_SERVER_USERNAME=ace0777
      - CONFIG_SERVER_PASSWORD=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
      - PORT=8888
    ports:
      - "8888:8888"
    expose:
      - 8888
    networks:
      - supportflow

  service-discovery:
    image: ace0777/supportflow-service-discovery
    container_name: 'service-discovery'
    environment:
      - CONFIG_SERVER_URI=config-server:8888
      - PORT=8761
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - supportflow
    depends_on:
      - config-server
    links:
      - config-server

networks:
  supportflow:
    driver: bridge
