spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      uri: ${CONFIG_SERVER_URI}
eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: ${EUREKA_SERVER_URI}
server:
  port: ${SERVER_PORT:8765}
