spring:
  application:
    name: 'user-service-api'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}

eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true