spring:
  application:
    name: 'supportflow-bff'
  cloud:
    config:
      uri: 'config-server'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}

server:
  port: ${PORT:8762}
