spring:
  application:
    name: 'supportflow-bff'
  cloud:
    config:
      uri: 'config-server'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true