spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${CONFIG_SERVER_URI}
          username: ${CONFIG_SERVER_USERNAME}
          password: ${CONFIG_SERVER_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}
      registerWithEureka: true
      fetchRegistry: true
server:
  port: ${SERVER_PORT:8888}