spring:
  profiles:
    active: ${PROFILE_ACTIVE}
  application:
    name: 'auth-service-api'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}

